version: "3.8"

services:
  SERVICE_NAME:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:11.1.1-devel-ubuntu20.04
        - PYTHON_VERSION=3.8
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ../../
      dockerfile: environments/docker/Dockerfile
    shm_size: '2gb'
    tty: true
    volumes:
        - ../../:/home/${USER_NAME}/${PROJECT_NAME}
    ports:
        - 8002:8002